### ISSUE TITLE
Progress bar background does not have proper color

### ISSUE THREAD

**Issue by ironcev** [sharpenrocks/Sharpen#1]
The color used to be black with white text on the Dark VS Theme. It is gray now and the text is not visible:

![image](https://user-images.githubusercontent.com/4142833/32949754-400445a4-cba4-11e7-81ae-903454e7a1ca.png)

It looks like this happened when we switched to tree view instead of list view.
Analyse the changes between 2f4fddd92d627ace188d10046a740b6d9035173d and 9b63ac20999e2537a92fb6866218c9e222bad227.

**Comment by kurtanr** [comment]
Wanted to help out a bit, and since I am familiar with WPF, this looked like a nice issue to start with...

I am using VisualStudio 2019 Community Edition 16.2.0 and I was not able to reproduce the issue on master branch. Then I went to the suggested commit which introduced the issue (9b63ac2) and built the installer from that commit. At that time (version 0.1), Sharpen did not support VS2019, so to make the installer work, I had to do some change in "source.extension.vsixmanifest" and had to update some nugets. The issue still could not be reproduced.

As a reference, I am attaching how the progress bar background looks in VS2019:

![theme_dark](https://user-images.githubusercontent.com/36173263/62287584-800e7c00-b45a-11e9-8fa5-c9f41745ddcf.png)

Maybe the issue was fixed by Microsoft when they fixed some issue in Visual Studio.
Can you still reproduce the issue?

**Comment by ironcev** [comment]
Thanks for your contribution @kurtanr! I've just tried to reproduce the issue in VS2017 and VS2019 on three different themes (Dark, Light, and Blue) and I was not able to reproduce the issue.

![image](https://user-images.githubusercontent.com/4142833/62314843-46f2fd80-b494-11e9-960c-08343f5e7649.png)

![image](https://user-images.githubusercontent.com/4142833/62314702-e6fc5700-b493-11e9-9828-100f3e02d1c6.png)

![image](https://user-images.githubusercontent.com/4142833/62314743-03988f00-b494-11e9-8b41-ce9ac9f724c1.png)

Even more, I was switching the theme while the progress bar was running and everything worked fine. The "Please wait" dialog was changing look and feel as expected.

My assumption is that the issue was connected to #15. The #15 was blocking VS UI and I guess also affected rendering.

Since this issue cannot be reproduced any more I'll close it.

Thanks once again for your contribution!
