### ISSUE TITLE
dependency alert: Visual Studio MPF 15.0 - already installed MPF 16.0

### ISSUE THREAD

**Issue by LeoJHarris** [sharpenrocks/Sharpen#21]
Hi I tried installing into VS2019 but was giving me a dependency alert: Visual Studio MPF 15.0, this is despite the fact I already have Visual Studio MPF 16.0 which I checked in the C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\CommonExtensions\Platform\Visual Studio MPF directory.

Is there reason why it wont accept v16.0? Is it hard coded to use v15.0?

**Comment by ironcev** [comment]
Looks like VS2019 internal issue that is already fixed in the upcoming releases of VS 2019. See:
https://developercommunity.visualstudio.com/comments/440978/view.html
https://developercommunity.visualstudio.com/comments/438377/view.html

But anyhow I am working right not on supporting both VS 2017 and VS 2019 in the same package.

**Comment by ironcev** [comment]
Fixed in [Sharpen v0.8.0](https://github.com/sharpenrocks/Sharpen/releases/tag/v0.8.0).
