### ISSUE TITLE
Add option to ignore CompilerGenerated code

### ISSUE THREAD

**Issue by Thieum** [sharpenrocks/Sharpen#35]
It would be nice to be able to ignore classes and/or methods marked with the [CompilerGenerated](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.compilergeneratedattribute?view=netframework-4.8) attribute, since this code cannot be improved, without it being regenerated with the previous syntax.

**Comment by ironcev** [comment]
Hi @Thieum, thanks for the proposal! Sharpen already ignores generated code, but on the file level. It supports a very simple heuristics with a comment already in code that we want to have it configurable and more powerful (see [GeneratedCodeDetection.cs](https://github.com/sharpenrocks/Sharpen/blob/7078c7d5418777a49fa102eed44879622ab85c79/src/Sharpen.Engine/Extensions/CodeDetection/GeneratedCodeDetection.cs#L8)).

I wasn't thinking about the `CompilerGenerated` attribute though, because I've actually never seen it in code. It is usually added to the metadata of the elements in assemblies generated by the compiler like e.g. [the classes that implement lambdas and closures](https://sharplab.io/#v2:D4AQTAjAsAUCDMACciDCiDetE+UkALIgLIAUAlJtrjSAKwA8AlgHYAuAfIgIaIC8iCvy4AGANzUcAX1hSgA=).

Do you maybe have a concrete example of a code that uses the `CompilerGenerated` attribute?

**Comment by ironcev** [comment]
Hi @Thieum, thanks for the proposal! Sharpen already ignores generated code, but on the file level. It supports a very simple heuristics with a comment already in code that we want to have it configurable and more powerful (see [GeneratedCodeDetection.cs](https://github.com/sharpenrocks/Sharpen/blob/7078c7d5418777a49fa102eed44879622ab85c79/src/Sharpen.Engine/Extensions/CodeDetection/GeneratedCodeDetection.cs#L8)).

I wasn't thinking about the `CompilerGenerated` attribute though, because I've actually never seen it in code. It is usually added to the metadata of the elements in assemblies generated by the compiler like e.g. [the classes that implement lambdas and closures](https://sharplab.io/#v2:D4AQTAjAsAUCDMACciDCiDetE+UkALIgLIAUAlJtrjSAKwA8AlgHYAuAfIgIaIC8iCvy4AGANzUcAX1hSgA=).

Do you maybe have a concrete example of a code that uses the `CompilerGenerated` attribute?

**Comment by Thieum** [comment]
@ironcev I thought I did, but those were manually added to the result of a protocol buffer file generated by the protocol buffer compiler, after investigation. I will open a ticket in protobuf, to check if that's something of interest to add to the compiler on their side. That kinda lowers the interest of this ticket for both of us at the moment, since I don't have a concrete example that would require this feature :(

**Comment by Thieum** [comment]
Also the proper attribute to use might be [GeneratedCodeAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.codedom.compiler.generatedcodeattribute?view=netframework-4.8) since CompilerGenerated is used by the c# compiler itself as you pointed out, not by third party tools.

**Comment by Thieum** [comment]
I'll close this issue for now and revisit if a proper use case arises.

**Comment by ironcev** [comment]
Hi @Thieum, I just wanted to say thanks for pointing out the `GeneratedCodeAttribute`. My original idea was to have the configuration settings similar to those in ReSharper:

![image](https://user-images.githubusercontent.com/4142833/71498302-1e610b00-285c-11ea-8bdd-312ca4426740.png)

Once the feature gains more on relevance I will for sure add support for the `GeneratedCodeAttribute` as well. Thanks!
